version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379" #expose redis port to host
    networks:
      - app-network 
  
  node-app:
    image: node:18-alpine
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge